stu_id = input("ป้อนรหัสนักศึกษา:")
stu_name = input("ป้อนชื่อนักศึกษา: ")
stu_birth_year = input("ปีเกิด: ")
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print(f'ยินดีต้อนรับ {stu_id} {stu_name} สู่ SAU')
print(f'คุณเกิดปี {stu_birth_year} แปลว่าคุณมีอายุ {2023 - int (stu_birth_year)}ปี')
print('ใช้ , ~~~~~~~~~~~~')
print('ยินดีต้อนรับ' ,(stu_id) ,(stu_name), 'สู่ SAU')
print('คุณเกิดปี' ,(stu_birth_year), 'แปลว่าคุณมีอายุ' ,(2023 - int (stu_birth_year)),'ปี')
print('ใช้ + ~~~~~~~~~~~~')
print('ยินดีต้อนรับ '+str (stu_id)+' '+str (stu_name)+' สู่ SAU')
print('คุณเกิดปี '+str (stu_birth_year)+' แปลว่าคุณมีอายุ '+str (2023 - int(stu_birth_year))+'ปี') 
print('ใช้ Format ~~~~~~~~~~~~~~~~~~~~~~~~~~')
print('ยินดีต้อนรับ {} {} สู่ SAU' .format(stu_id,stu_name))
print("คุณเกิดปี {} แปลว่าคุณมีอายุ {} ปี" .format(stu_birth_year,2023 - int (stu_birth_year)))